import Image from "next/image";
import Link from "next/link";
import { Camera, Mail, Video } from "lucide-react";

export default function Footer() {
  return <footer className="w-full max-w-full overflow-x-clip bg-zinc-950 text-white"><div className="mx-auto w-full max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="grid min-w-0 gap-10 border-b border-white/10 pb-10 md:grid-cols-[1.4fr_1fr_1fr_1fr]">
    <div><Image src="/images/logo.PNG" alt="Jelajah Subang" width={300} height={300} className="h-auto w-52 object-contain sm:w-64" /><p className="mt-4 max-w-sm text-sm leading-6 text-white/75">Portal untuk menemukan destinasi, cerita lokal, kuliner, dan produk kreatif dari Kabupaten Subang.</p><div className="mt-5 flex gap-2"><a href="https://www.instagram.com/jelajahsubang/" target="_blank" rel="noreferrer" aria-label="Instagram" className="rounded-full border border-white/20 p-2.5 text-white/80 hover:bg-white/10"><Camera className="h-4 w-4" /></a><a href="https://www.youtube.com/@jelajahsubang" target="_blank" rel="noreferrer" aria-label="YouTube" className="rounded-full border border-white/20 p-2.5 text-white/80 hover:bg-white/10"><Video className="h-4 w-4" /></a><a href="mailto:info@jelajahsubang.com" aria-label="Email" className="rounded-full border border-white/20 p-2.5 text-white/80 hover:bg-white/10"><Mail className="h-4 w-4" /></a></div></div>
    <div><h3 className="text-xs font-black uppercase tracking-widest text-white/70">Jelajahi</h3><nav className="mt-4 space-y-3 text-sm text-white/80"><Link className="block hover:text-white" href="/destinasi">Destinasi</Link><Link className="block hover:text-white" href="/blog">Blog</Link><Link className="block hover:text-white" href="/shop">Shop</Link></nav></div>
    <div><h3 className="text-xs font-black uppercase tracking-widest text-white/70">Layanan</h3><nav className="mt-4 space-y-3 text-sm text-white/80"><Link className="block hover:text-white" href="/sharelok">Sharelok Kuliner</Link><Link className="block hover:text-white" href="/tentang">Tentang Kami</Link></nav></div>
    <div><h3 className="text-xs font-black uppercase tracking-widest text-white/70">Mitra</h3><div className="mt-4 space-y-3 text-sm text-white/80"><a className="block hover:text-white" href="https://www.subangkab.go.id/" target="_blank" rel="noreferrer">Pemkab Subang</a><a className="block hover:text-white" href="https://www.disparbud.subangkab.go.id/" target="_blank" rel="noreferrer">Disparbud Subang</a></div></div>
  </div><div className="flex flex-col gap-2 pt-6 text-xs text-white/65 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} Jelajah Subang. Semua hak dilindungi.</p><p>Dibuat untuk tumbuh bersama Subang.</p></div></div></footer>;
}
