"use client";

import { useCallback, useEffect, useState } from "react";
import { BadgePercent, Loader2, Pencil, Plus, Trash2, X } from "lucide-react";

/* eslint-disable react-hooks/purity -- promo expiry reflects the current clock at render time. */

interface Promo { id: string; code: string; description: string | null; discountType: string; discountValue: number; maxDiscount: number; minOrder: number; usageLimit: number; usedCount: number; expiresAt: string; isActive: boolean }
const emptyForm = { code: "", description: "", discountType: "PERCENT", discountValue: 10, maxDiscount: 0, minOrder: 0, usageLimit: 0, expiresAt: "", isActive: true };
const rupiah = (value: number) => `Rp ${value.toLocaleString("id-ID")}`;

export default function PromosAdminPage() {
  const [promos, setPromos] = useState<Promo[]>([]); const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/sharelok/promos"); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Gagal memuat promo"); setPromos(data); setLoading(false); }, []);
  useEffect(() => { Promise.resolve().then(load).catch((error) => { setMessage(error.message); setLoading(false); }); }, [load]);
  function reset() { setForm(emptyForm); setEditingId(null); setMessage(""); }
  function edit(item: Promo) { setEditingId(item.id); setForm({ code: item.code, description: item.description || "", discountType: item.discountType, discountValue: item.discountValue, maxDiscount: item.maxDiscount, minOrder: item.minOrder, usageLimit: item.usageLimit, expiresAt: new Date(item.expiresAt).toISOString().slice(0, 16), isActive: item.isActive }); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); try { const response = await fetch("/api/sharelok/promos", { method: editingId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...(editingId ? { id: editingId } : {}), ...form }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Gagal menyimpan promo"); reset(); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Gagal menyimpan promo"); } finally { setSaving(false); } }
  async function remove(item: Promo) { if (!window.confirm(`Hapus promo ${item.code}?`)) return; const response = await fetch(`/api/sharelok/promos?id=${item.id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) return setMessage(data.error || "Gagal menghapus promo"); await load(); }
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Marketing</p><h2 className="mt-1 text-2xl font-black">Kode promo</h2><p className="mt-1 text-sm text-zinc-500">Atur diskon, minimal belanja, kuota, dan masa berlaku promo.</p></div>
    <form onSubmit={submit} className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h3 className="font-black">{editingId ? "Edit promo" : "Promo baru"}</h3>{editingId && <button type="button" onClick={reset}><X className="h-5 w-5" /></button>}</div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3"><input required placeholder="Kode, contoh HEMAT10" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value.toUpperCase() })} className="rounded-xl border border-zinc-200 px-3 py-2.5 text-sm font-bold uppercase" /><input placeholder="Deskripsi promo" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="rounded-xl border border-zinc-200 px-3 py-2.5 text-sm" /><select value={form.discountType} onChange={(e) => setForm({ ...form, discountType: e.target.value })} className="rounded-xl border border-zinc-200 px-3 py-2.5 text-sm"><option value="PERCENT">Persentase (%)</option><option value="FIXED">Potongan rupiah</option></select><input required type="number" min="0" placeholder="Nilai diskon" value={form.discountValue} onChange={(e) => setForm({ ...form, discountValue: Number(e.target.value) })} className="rounded-xl border border-zinc-200 px-3 py-2.5 text-sm" /><input type="number" min="0" placeholder="Maks. diskon (0 = bebas)" value={form.maxDiscount} onChange={(e) => setForm({ ...form, maxDiscount: Number(e.target.value) })} className="rounded-xl border border-zinc-200 px-3 py-2.5 text-sm" /><input type="number" min="0" placeholder="Minimal belanja" value={form.minOrder} onChange={(e) => setForm({ ...form, minOrder: Number(e.target.value) })} className="rounded-xl border border-zinc-200 px-3 py-2.5 text-sm" /><input type="number" min="0" placeholder="Kuota (0 = tanpa batas)" value={form.usageLimit} onChange={(e) => setForm({ ...form, usageLimit: Number(e.target.value) })} className="rounded-xl border border-zinc-200 px-3 py-2.5 text-sm" /><input required type="datetime-local" value={form.expiresAt} onChange={(e) => setForm({ ...form, expiresAt: e.target.value })} className="rounded-xl border border-zinc-200 px-3 py-2.5 text-sm" /></div><label className="mt-4 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })} className="h-4 w-4 accent-emerald-600" /> Promo aktif</label>{message && <p className="mt-3 text-sm text-red-600">{message}</p>}<button disabled={saving} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}{editingId ? "Simpan promo" : "Buat promo"}</button></form>
    <div className="grid gap-3">{loading ? <div className="rounded-2xl bg-white p-10 text-center text-sm text-zinc-500">Memuat promo...</div> : promos.map((item) => { const expired = new Date(item.expiresAt).getTime() <= Date.now(); return <div key={item.id} className="flex flex-wrap items-center gap-4 rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-amber-100 text-amber-700"><BadgePercent className="h-5 w-5" /></div><div className="min-w-44 flex-1"><div className="flex items-center gap-2"><span className="font-black">{item.code}</span><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${item.isActive && !expired ? "bg-emerald-100 text-emerald-700" : "bg-zinc-100 text-zinc-500"}`}>{expired ? "KEDALUWARSA" : item.isActive ? "AKTIF" : "NONAKTIF"}</span></div><p className="text-xs text-zinc-500">{item.discountType === "FIXED" ? rupiah(item.discountValue) : `${item.discountValue}%`} · Min. {rupiah(item.minOrder)} · Terpakai {item.usedCount}{item.usageLimit ? `/${item.usageLimit}` : ""}</p><p className="mt-1 text-[10px] text-zinc-400">Berakhir {new Date(item.expiresAt).toLocaleString("id-ID")}</p></div><button onClick={() => edit(item)} className="rounded-lg p-2 text-zinc-500 hover:bg-zinc-100"><Pencil className="h-4 w-4" /></button><button onClick={() => remove(item)} className="rounded-lg p-2 text-red-500 hover:bg-red-50"><Trash2 className="h-4 w-4" /></button></div>; })}</div>
  </div>;
}
